version: '3.1'

services:

  db:
    container_name: cms_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - testnet

  migrations:
    build:
      context: .
    container_name: cms_migrations
    command: bash -c 'sleep 5 && make migrate'
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_DSN=postgresql://postgres:postgres@db:5432/postgres
    networks:
      - testnet

  tests:
    build:
      context: .
    container_name: cms_tests
    command: bash -c 'sleep 10 && make test_local'
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_DSN=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    networks:
      - testnet


networks:
  testnet:
    driver: bridge
