services:
# TODO: implement proper test run
  app:
    container_name: cms_app
    build:
      context: docker
    networks:
      - testnet

  db:
    container_name: cms_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
